Update 'docs/CONTRIBUTING.md'
yaichenbaum/Quick-Pad pull request #470
Opened 2021-07-16 14:05 UTC by Hedreon

To replace references of 'master' to 'Main'

2021-07-16 14:06 UTC, Hedreon commented
If any problems, comment in the PR.

2021-07-19 02:10 UTC, yaichenbaum requested changes

2021-07-19 02:10 UTC, yaichenbaum commented on docs/CONTRIBUTING.md
> +To get started, create a fork of the repository on GitHub. You will need to do that to make any changes since the Quick Pad repo is restricted to a few contributors of the app. If you decide to make
```suggestion
To get started, create a fork of the repository on GitHub. You will need to do that to make any changes. If you decide to make a change you should always base it off the `Main` branch. Once your change is completed, you can open a pull request in which we will review and merge if approved.
```

2021-07-19 12:23 UTC, Hedreon commented
Suggestion merged.

2021-07-19 20:30 UTC, yaichenbaum requested changes

2021-07-19 20:30 UTC, yaichenbaum commented on docs/CONTRIBUTING.md
> +To get started, create a fork of the repository on GitHub. You will need to do that to make any changes. If you decide to make a change you should always base it off the `Main` branch. Once your chan
```suggestion
To get started, create a fork of the repository on GitHub. You will need to do that to make any changes. If you decide to make a change you should always base it off the `Main` branch. Once your change is completed, you can open a pull request which we will review and merge if approved.
```

2021-07-23 04:12 UTC, yaichenbaum approved these changes

2021-07-23 04:12 UTC, yaichenbaum commented
Thank you!

2021-07-23 04:12 UTC, merged